name: Docker Build and Run

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: docker login
        env:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run : |
          docker login -u $username -p $password
        
      - name: docker build  
        run: |
          docker build <./directory/to/folder> -t <image:tag>   
      
      - name: docker push
        run: |
          docker push <image:tag>
          
      - name: docker run 
        run: |
          docker run -d <image:tag>
